### ISSUE TITLE
6. Tip Calculator Logic

### ISSUE THREAD

**Issue by codejunkie1001** [MakeSchool-Tutorials/Tip-Calculator-Swift4#11]
The code in the screenshot (Create Calculate Button) does not match the code a bit later in the Create Calculate Action...my code breaks at this point...also not sure if if’s a Swift 4.0 issue, but does not compile at this point (“#selector(calculateButtonTapped)” creates an error).

**Comment by ellojess** [comment]
Thanks for bringing this issue up, it has now been resolved ✅
