### ISSUE TITLE
7. Theming and Styling

### ISSUE THREAD

**Issue by AbdollahKhezri** [MakeSchool-Tutorials/Tip-Calculator-Swift4#12]
In 👉 Implementing Our IBAction:
need to correct the code 👇
@IBAction func switchToggled(_ sender: UISwitch) {
        if sender.isOn {
            setTheme(isDark: sender.isOn)
        }
        else{
// 👉 Toggle off
           setTheme(isDark: false)
        }
    }

**Comment by ellojess** [comment]
Thanks for bringing this issue up, it has now been resolved ✅
