### ISSUE TITLE
6. Tip Calculator Logic

### ISSUE THREAD

**Issue by hanwill00** [MakeSchool-Tutorials/Tip-Calculator-Swift4#7]
They Keypad doesn't show up unless I open the simulator and follow hardware -> keyboard 
and deselect “connect hardware keyboard”. Hung me for a little bit

**Comment by hanwill00** [comment]
error Can't find keyplane that supports type 8 for keyboard comes up in console

**Comment by codejunkie1001** [comment]
Agreed, the keypad does not show up after coding the “Calculate Tip” accessory view. It shows up at the bottom of the screen, but no keypad. Consistent across various iPhone simulators.
